### PR TITLE
New endpoints + Delete sample responses + Naming corrections 

### PR DESCRIPTION
**Pull request by Mingyang-Li-MATTR**
## ⚠️ Changes:
1. Added `new requests` for endpoints related to`inbox` following the latest `env` in `master` branch
2. Fixed naming conventions and request URLs for existing endpoints related to`Messaging` (encrypt, sign, sending msgs)
3. Added a `new request` for `decrypt-message`
4. Deleted ALL sample responses for ALL endpoints - For ease of maintenance & ease of use for API users to save their own sample responses
5. Added `new-requests` for `Credentials`, `Revocation` & `Presentations`

## To view changes:
Follow readme doc from `/postman` folder to import both environment file & the collection

### CODE REVIEW

**Comment by Mingyang-Li-MATTR** [comment]
Continuation for #93

**Comment by PreetPatel** [comment]
I don't think I understand decision #5. The API's need to include sample requests by default. I do agree to not have responses but it needs to have requests.

**Comment by Mingyang-Li-MATTR** [comment]
@PreetPatel  Sample response body for `POST` and `PUT` requests are added back in to the collection. After looking at postman collections from other companies, it does make sense to keep them in request bodies as samples.

**Review by PreetPatel — APPROVED** [review]
Looks good to me. Please squash and merge. 
Also address small issues in your other PR as discussed. And add a comment here once its merged

**Comment by Mingyang-Li-MATTR** [comment]
Will be fixing minor issues in PR #101

**Pull request merged**
